In [1]:
import torch

In [4]:
base = [1, 2, 3, 4, 5, 6]

In [7]:
a = torch.tensor(base).view(2, 3)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
b = torch.tensor(base).view(3,2)
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
a @ b

tensor([[22, 28],
        [49, 64]])