In [2]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Mon_Oct_24_19:12:58_PDT_2022
Cuda compilation tools, release 12.0, V12.0.76
Build cuda_12.0.r12.0/compiler.31968024_0


In [3]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))


True
Quadro RTX 5000


In [4]:
base = [1, 2, 3, 4, 5, 6]

In [7]:
a = torch.tensor(base).view(2, 3)
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
b = torch.tensor(base).view(3, 2)
b

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [9]:
a @ b

tensor([[22, 28],
        [49, 64]])